const roomGenerator = require('../util/roomIdGenerator.js');
const Room = require('../models/Room.js');

/*
The route for createRoom receives the database information for rooms and 
determines the name and id for the room based on the user's input in the
home page. 

The randomRoomName field is set to false if the user creates a name for 
the room. If the user selects to generate a random room name then 
randomRoomName will be set to true. 

The newRoomId is assigned to the roomName typed by the user or the random
name generated by the roomIdGenerator() function. This is done by the 
ternary operator on randomRoomName.

If there is any issue assigning the newRoomId, then it will redirect to home.

The new room is saved in the database.
*/
async function createRoom(request, response) {
    const {roomName, randomRoomName} = request.body;
    console.log(request.body);
    const newRoomId = randomRoomName === 'false' ? roomName : roomGenerator.roomIdGenerator();

    if (!newRoomId)
        return response.redirect('/');

    const newRoom = new Room({roomId: newRoomId});

    try {
        await newRoom.save();
        response.redirect(`/${newRoomId}`);
    }
    catch (err) {
        console.error(err);
        response.status(500).send('Server Error in Creating Room');
    }
}

module.exports = {
    createRoom
};